// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID       int64
	Name     string
	Email    string
	Username string
}

type Commit struct {
	Hash         string
	AuthorID     int64
	Message      string
	Url          pgtype.Text
	CreatedAt    pgtype.Timestamptz
	RepositoryID int64
}

type Intent struct {
	ID         uuid.UUID
	Repository string
	Since      pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	IsActive   bool
}

type Repository struct {
	ID         int64
	Watchers   int32
	Stargazers int32
	FullName   string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Language   pgtype.Text
	Forks      int32
}
