version: "2"
sql:
  - engine: "postgresql"
    queries: "../internal/explorer/repository/postgres/queries"
    schema: "../internal/explorer/repository/postgres/migrations"
    gen:
      go:
        package: "sqlc"
        out: "../internal/explorer/repository/postgres/sqlc"
        sql_package: "pgx/v5"
        overrides:
          - db_type: "uuid"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"